### PR TITLE
fixes #8 : updated transitive packages

### LINKED ISSUE #8: Fails to compile with Node 12.4.0
`npm I` fails with compile errors using Node v12.4.0.

### PR DESCRIPTION
**Pull request by joeyguerra**
I ran `npm audit fix --force` to update all the transitive dependencies to fix the compilation errors.

### CODE REVIEW

**Comment by rtilikay** [comment]
Thank you for fixing these errors!
